
diff_engine: segment_matcher

tokenizers:
  wikitext_split:
    module: deltas.tokenizers.wikitext_split

diff_engines:
  segment_matcher:
    class: deltas.algorithms.SegmentMatcher
    segmenter: western_psw
    tokenizer: wikitext_split

segmenters:
  western_psw:
    class: deltas.segmenters.ParagraphsSentencesAndWhitespace
